Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-085925f297f89fce1 # Ubuntu Server 18.04 LTS (HVM), SSD Volume Type in N.Virginia
      Tags:
        - Key: Author
          Value: Alexandre Sueiro
        - Key: Project
          Value: EstudoAWS - CloudFormation
        - Key: Versao
          Value: Instance - 01
      SecurityGroups: 
        - !Ref SGDMZPersonalSiteCF
  SGDMZPersonalSiteCF:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0